### PR TITLE
Added Collect task support

### PR DESCRIPTION
**Pull request by g-bougard**
It would be nice to have Collect task in the next 2.3.x windows installer release.
I hope I missed nothing important.
Thanks ;)

### CODE REVIEW

**Comment by tabad** [comment]
Hello Guillaume,

This is the same commit than this one [8d4ff1a1619974e4c02db1cfd6eb78a0c8ccd66b](https://github.com/tabad/fusioninventory-agent-windows-installer/commit/8d4ff1a1619974e4c02db1cfd6eb78a0c8ccd66b), isn't it?

**Comment by g-bougard** [comment]
Hello Tabad, argh, I didn't see that work before... Sorry. Btw this PR is really for 2.3.x branch and to have Collect task included in 2.3.17 release. Also I can see few difference you may want to backport in master branch. So this is not really the same commit, but yes this is mostly the same...
I really should have checked diff between master & 2.3.x here. ;)

**Comment by tabad** [comment]
Hello Guillaume,

I have reread your patch I must say to you a couple of things. The first one is that I think you have done a great job (at the beginning I thought you copied the code, I apologize); the second one is "thank you", thank you for read my code. ;)

Your request and my past commits in master branch [9acc9ad6ab](https://github.com/tabad/fusioninventory-agent-windows-installer/commit/9acc9ad6aba8fd48345505712cb191d5d953b0e2) and [8d4ff1a161](https://github.com/tabad/fusioninventory-agent-windows-installer/commit/8d4ff1a1619974e4c02db1cfd6eb78a0c8ccd66b) are close to be the same thing. There are basically five differences: [one](https://github.com/g-bougard/fusioninventory-agent-windows-installer/commit/5ca8a85a6da6cefba4356b0bfb974f4482494f7b#diff-a1ec083403753562e43074d6dee666f1R124), [two](https://github.com/g-bougard/fusioninventory-agent-windows-installer/commit/5ca8a85a6da6cefba4356b0bfb974f4482494f7b#diff-d6ae2f2125ab90a96ead5f2adb164731R144), [three](https://github.com/tabad/fusioninventory-agent-windows-installer/commit/9acc9ad6a#diff-16fd86d65e1611db40cdc5df45bcd4f6R268), [four](https://github.com/tabad/fusioninventory-agent-windows-installer/commit/9acc9ad6a#diff-ac109350f2e40bf4f36e15802dd2d0ddR142) and [five](https://github.com/g-bougard/fusioninventory-agent-windows-installer/commit/5ca8a85a6da6cefba4356b0bfb974f4482494f7b#diff-cd5471b807ad9cc89e7207db5a7e9773), whether we don't count the misprint _licence_. ;)

Well, I will mix all the changes and will make the commit; the next release 2.3.17 will have the new Collect task, and perhaps the new [Strawberry Perl Portable Edition v5.22.0.1](http://strawberryperl.com/releases.html).

Again, thanks for your job.

Best regards,

**Comment by tabad** [comment]
Hello Guillaume,

I think I have found the main difference, `./bin/fusioninventory-collect` doesn't exist in the current 2.3.x branch.

Best regards,

**Comment by tabad** [comment]
Hello Guillaume,

The support for Collect task is ready. Thank you for your interest and your help.

**Pull request closed without merging**
